export const SET_RESTAURANT = 'SET_RESTAURANT';

export const ADDING_CART_ITEMS_TO_SERVER = 'ADDING_CART_ITEMS_TO_SERVER';

export const FETCHING_CART_ITEMS_FROM_SERVER = 'FETCHING_CART_ITEMS_FROM_SERVER';

export const DELETING_CART_ITEMS_FROM_SERVER = 'DELETING_CART_ITEMS_FROM_SERVER';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADDING_USER_DATA_TO_SERVER = 'ADDING_USER_DATA_TO_SERVER';

export const FETCHING_USER_DATA_FROM_SERVER = 'FETCHING_USER_DATA_FROM_SERVER';